### ISSUE TITLE
GetMonitorsQuery.Enabled

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#109]
1) is currently a string field, should be a *bool (bool but with a null value that we can use to specify no particular condition, which a plain bool doesn't support)
2) doesn't seem to be used in any of the actual sql queries
3) once the above are fixed, should also make sure the alert scheduler queries with enabled: true

**Comment by nopzor1200** [comment]
query format for alerting allows some functionality that backend is not taking advantage of.

**Comment by Dieterbe** [comment]
note that as of 6c258ca3 we use GetMonitorsForAlerts,
we can probably just hardcode querying only for the enabled ones.

@nopzor1200 what do you mean?

**Comment by woodsaj** [comment]
This has been fixed in https://github.com/raintank/grafana/commit/8414c756d100fcc4429684c6bc1cecf3ba8f0500

left the field as a string field as it it is parsed via url form, not json. so we need to treat it as a string and strconv.parseBool() as there is no standard way for specifying bool via query params. (0|1, true|false, etc...)

Also updated the GetMonitorsForAlerts query to only return enabled monitors.
