### ISSUE TITLE
interesting errors on startup

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#114]
```
2015/05/18 15:11:13 [I] Database: mysql, ConnectionString: grafana:password@tcp(mysql:3306)/grafana?charset=utf8
2015/05/18 15:11:13 [I] Migrator: Starting DB migration
2015/05/18 15:11:13 [I] Listen: http://0.0.0.0:80
2015/05/18 15:11:16 http: response.WriteHeader on hijacked connection
2015/05/18 15:11:16 [I] Completed /socket.io/ 400 Bad Request in 476.259µs
2015/05/18 15:11:16 [I] New connection for PublicTest owned by OrgId: 1
searching for sessions for collector 1
2015/05/18 15:11:16 [I] Collector 1 refreshing
2015/05/18 15:11:16 [I] sending refresh to hRrw0aurcAGqN5MUAU_4
2015/05/18 15:11:18 [I] recieved event from PublicTest
2015/05/18 15:11:18 [D] updating state of monitor: 1 from publictest
2015/05/18 15:11:18 http: response.WriteHeader on hijacked connection
2015/05/18 15:11:18 [I] Completed /socket.io/ 400 Bad Request in 438.448µs
```

i wonder what's up with the `http: response.WriteHeader on hijacked connection` and the `Completed /socket.io/ 400 Bad Request` and if they are safe to ignore?
been seeing these in master branch on dev stack for a while.

**Comment by woodsaj** [comment]
This has something to do with the socket.io integration.

**Comment by woodsaj** [comment]
This is due to socket.io sending a httpBadRequest response every time a connection is established.  I cant see any reason for why it is doing this.

This is just another example of why we should move away from go-socket.io and just use websockets directly.   Though that changes is not trivial and can wait for another day.This is due to socket.io sending a httpBadRequest response every time a connection is established.  I cant see any reason for why it is doing this.

This is just another example of why we should move away from go-socket.io and just use websockets directly.   Though that changes is not trivial and can wait for another day.
