### ISSUE TITLE
collector errors on startup

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#117]
after stopping and starting the dev stack a few times i got this:
```
2015/05/18 16:30:37 [log.go:198 writerMsg()] [E] Failed to initialize collector.%!(EXTRA *errors.errorString=Collector not found)
2015/05/18 16:30:37 [log.go:198 writerMsg()] [E] Failed to initialize collector.%!(EXTRA *errors.errorString=Collector not found)
2015/05/18 16:30:37 [collector.go:72 AddCollector()] [E] Failed to add collector: Error 1062: Duplicate entry '1-publictest' for key 'UQE_collector_org_id_slug'
```

saw these errors while running latest master code.  
i may have started the first time (when adding collector) with litmus-alerting-v3 code, though that shouldn't matter.

**Comment by woodsaj** [comment]
This is pretty much expected behavior right now. Currently when a collector tries to connect with a collectorName that does not exist, the connection is rejected. The collector then creates the collector via an API call and tries to connect again.  If two collector processes are running, then they will both have their connections rejected and both will try and create the new collector at the same time, obviously only 1 of those attempts will work.

I will re-factor this so that the backend creates the new collector instead.

**Comment by woodsaj** [comment]
fixed in https://github.com/raintank/grafana/commit/40dfb82225bd4ca9299bf0d8e2d6a4d703b1cd2c
