### ISSUE TITLE
Addition of Health & Alerting sections to New Endpoint & Endpoint Config

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#122]
The inclusion of Health & Alerting, per endpoint.

**Comment by mattttt** [comment]
Backend tracked on Issue https://github.com/raintank/grafana/issues/110

**Comment by mattttt** [comment]
Going to be working on this today to not hold up @Dieterbe

**Comment by mattttt** [comment]
Mockup of the Health and Alerting sections, along with new collector config. 

A few things of note. 

- I said "report issues" to keep things vague. I'd like to have some sort of tool-tip that explains what issues are. @Dieterbe: Is that something you can summarize for me before you go, and I'll revise the copy for the interface. 

- The email text area will be comma separated initially, and then we'll implement the gmail/tag-style email addresses.

![endpoint-config-alerting](https://cloud.githubusercontent.com/assets/2886187/7729537/59558b8e-fee3-11e4-8c44-72b29d24d745.png)

**Comment by bulletfactory** [comment]
:+1:

**Comment by Dieterbe** [comment]
* "more than x" should be "x or more", otherwise can be misleading.
* just a reminder that we agreed there would be an "enabled" flag so alerts could be temporarily turned off, while not loosing the filled in email addresses.
* report down should be mark as down, reporting implies to me actual email reports/notifications.
* report issues can be "fail to connect" (which is most true but doesn't tie in explicitly to the event overviews, but I think that's ok). otherwise could be something like "report connection errors".

**Comment by mattttt** [comment]
Thanks @Dieterbe, great feedback.

**Comment by mattttt** [comment]
A second pass, i think it's cleaner. 

![endpoint-config-alerting-v2](https://cloud.githubusercontent.com/assets/2886187/7731197/cbc612f2-feec-11e4-9c12-d4ff753eb572.png)

**Comment by mattttt** [comment]
These are done for the moment and sufficient to keep pushing dev along. Closing, and will open a new issue for tweaks. 

![screenshot 2015-05-25 15 18 17](https://cloud.githubusercontent.com/assets/2886187/7801346/49773c0a-02f1-11e5-9ca1-36d9eacda85b.png)

Commented out at the moment.
