### ISSUE TITLE
Litmus New User Onboarding

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#152]
I'd like to spend a morning going through the experience completely as a new signup and look for obvious issues. Since we're issuing people account manually atm, this would start with their first login, getting a first endpoint set up, and navigating around the dashboards.

**Comment by mattttt** [comment]
@woodsaj blocked on this atm because I cant seem to figure out how to create new orgs, even as an admin. I added a new user to the system, but get "Unathorized" message when logging in.

**Comment by nopzor1200** [comment]
So just to recap decisions made on the recent call:

1. We will ask for email and org name (?) for new users (very little else initially; @mattt made the point to minimize required information as much as possible which I very much agree with)

2.  We will generate a suggested domain name org.raintank.io that will automatically set the org context in their instance of Grafana when they go directly to this URL (similar to how slack does it). @woodsaj mentioned that we'll likely initially launch with a wildcard record but doing this from the beginning has two benefits:

 * Vanity coolness / ease of going to "their" URL
 * Future scaling/sharding/homing customers around different clusters, AZs, continents, etc etc

Just another thought:

1. What about asking them for an optional first endpoint to monitor? I kind of like this idea because that way when they first log in they will have their first endpoint already there and data already "live".  We could take a domain name on sign up and just add it as their first endpoint (with our default suggestions).

**Comment by Dieterbe** [comment]
re your suggestion, what if our default recommendations are not actually what they wanted? then they have to go back and change it anyway. that seems a bit messy because the old data is not at the resolution they wanted, they have to dig back to the config section, etc.

we actually have a pretty great "enter address, and look what we can auto-discover and you can fine-tune the details (or if you entered the wrong url it'll be obvious too)" UX inside of the product which I think we should not bypass because it's very valuable.
I would rather make sure we very smoothly guide them into and through this after they sign up and login.
or possibly do as you say (add endpoint during signup), but provide this same great UX into this step of the signup process, but then that might get complicated code wise and possibly redundant.

**Comment by nopzor1200** [comment]
That's a really good point Dieter...
