### ISSUE TITLE
Endpoint Config Enabled/Disabled Icons

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#156]
I think there's still room for improvement on the collapsed checks. Currently, if at least one check is enabled, I believe it implies that the others are not enabled. But if no checks are enabled, there are no affordances to illustrate that. 

Here's the beginning of an idea, which is to drive the monitoring icon into the check bar:

![screenshot 2015-05-28 23 36 58](https://cloud.githubusercontent.com/assets/2886187/7876070/d8deaa78-0593-11e5-8e66-2e7cb597250b.png)

Starting this ticket as a stub to continuing working on it.

**Comment by mattttt** [comment]
Here's a different take - a bit simpler. 

![screenshot 2015-05-28 23 51 16](https://cloud.githubusercontent.com/assets/2886187/7876102/78a0ec10-0594-11e5-8fb5-56a363b98ad3.png)

**Comment by bulletfactory** [comment]
I wonder if combining the two ideas would work. On one hand, I really like
having the larger icons on the left, next to the check type - at a glance I
know what's enabled. On the other hand, I like only noting what is not
enabled, instead of putting a label showing (in this instance) enabled 3
times. The blue color gives me pause - (I'm open to it) but seems like
we've established conventions for enabled/disabled - the light grey for
enabled and a dark grey for disabled. Maybe those icons should follow that
convention?

**Comment by mattttt** [comment]
The more I think about it, the less I'm liking the icon functionally. Though monitoring is main element to enable/disable; there are other parts of each section that could be disabled, but not represented there. 

Let's keep chewing on it.

**Comment by mattttt** [comment]
Second screenshot implemented in litmus-alerting-v3
