### ISSUE TITLE
alerting UI elements not rendering correctly.

### ISSUE THREAD

**Issue by woodsaj** [raintank/grafana#162]
Looks like the form modifications in master have messed with the placement of the alerting form elements.

@mattttt can you fix this up, doesn't look like it will take long.

the forms are in all of the dnsForm, pingForm, httpForm and httpsForm templates.

https://github.com/raintank/grafana/blob/litmus-alerting-v3/public/plugins/raintank/features/partials/dnsForm.html#L80

This is in the litmus-alerting-v3 branch (I merged master with this branch this morning so should be up-to-date)

**Comment by mattttt** [comment]
Style updates pushed in branch: litmus-alerting-v3

**Comment by mattttt** [comment]
I started to add "Alerting Enabled" into the check bar, but the Enable/Disabled for alerting on each check appears to be a single variable rather than on a per-check-basis:

<input class="rt-modal" id="http-alert-enabled1" type="checkbox" ng-model="monitors['alert'].enabled" ng-click="updateMonitor(monitors['http'])">

@woodsaj, will this be separated out?

**Comment by woodsaj** [comment]
yes, the notification settings haven't been wired up yet.

**Comment by mattttt** [comment]
Got it. Will hold tight.
