### ISSUE TITLE
I think we need to refactor the alerting-rabbitmq integration a bit.

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#264]
* the alert-jobqueue-internal.items/size statsd metrics were supposed to reflect the size and number of items of the internal job queue (channel), which it does, for `standalone`.
for `distributed()` we have two buffers: one with an instrumented capacity and size (channel), and rabbitmq, for which we have no metrics. we should instrument rabbitmq somehow and use a better name (perhaps `to-rabbit`) for the jobqueue channel the way it's used in the rabbitmq context.
* we should be able to see (and instrument via statsd) slow consumers (consumer being workers in standalone mode, and rabbitmq and workers in distributed mode). this requires rabbitmq being able to apply backpressure. right now, we have a consumeQueue in go which uses the same (permissive) capacity as the inbound jobqueue.  this means we pull out jobs potentially faster than the workers can handle, resulting in poor (and potentially extremely delayed) backpressure, limited visibility into what's going on, and potentially dataloss (messages should only be acknowledged to rabbitmq when they have been successfully processed). otherwise in case a worker crashes, messages read off the queue but not completely processed by a worker will get lost.
* finally, in the consumeQueue reader we're also writing statsd metrics here with the `alert-dispatcher.jobs-skipped-due-to-slow-jobqueue` key which is used for other things. I would like to take out the consumequeue entirely, and just have workers directly read new messages as they have capacity to process them, and only acknowledge them to the queue once they have been succesfully processed.

@woodsaj let me know what you think, does what i say sound possible? how would this work? an entire execution run as a callback to `consumer.Consume` ?

**Comment by woodsaj** [comment]
The current design was implemented as way to use rabbitmq as an intermediary between the dispatcher and executor by splitting the jobQueue into two channels, one publishing to rabbit and the other consuming from it.

 I agree that this has lots of room for improvement. 
As a first step, i think that we will need to split alerting.Executor() into a comsumer and processor.
in standalone mode, the consumer would consume from the jobQueue chan and process each job. In distributed mode, the consumer would use the existing rabbitmq consumer callback, but instead of just pushing the job to the jobQueue chan, it would instead execute it directly.  This would result in the rabbitmq message only being ack'ed once the job is finished.

**Comment by Dieterbe** [comment]
yep, something like that. self assigning..
