### ISSUE TITLE
Breadcrumb in top nav not working

### ISSUE THREAD

**Issue by bulletfactory** [raintank/grafana#33]
Endpoints and Collector links in the top nav should take you to endpoint list and collector list, respectively.

**Comment by woodsaj** [comment]
This needs to be handled by the topnav directive.

We probably need to add a sectionAction field or re-enable the commented out title link and update the topnav elements on the collector/endpoint pages to use title instead of section and to pass a titleAction

This is an upstream change so might be best to consult torkel.

**Comment by woodsaj** [comment]
this issue is not litmus specific and affects breadcrumbs for all grafana.
Matt can we get some direction on how we want this to work.

The topnav directive originally supported two breadcrum items.  'section' and 'title'.  The title field supported an optional 'titleAction' which should be a js function to execute when the title is clicked.
Currently in grafana the section header is only being used on the user profile page.  Most other pages are using the title header, but the rendering of this is currently commented out so the pages have no breadcrum.

Personally i would go with dropping the section text, title text and titleAction attributes and just add a sectionAction attribute which would allow the section icon to support clickable actions.

**Comment by nopzor1200** [comment]
Needs discussion.

Consistency is probably the most important things.

@mattttt Matt wants more formal breadcrumbs.

@woodsaj  points out that Grafana is not consistent.

**Comment by mattttt** [comment]
I still want more formal breadcrumbs and consistency in Grafana, and then inherit that in raintank.

**Comment by mattttt** [comment]
Closing this to address in Grafana
