### ISSUE TITLE
Prevent proxy data sources from hitting internal IP addresses

### ISSUE THREAD

**Issue by ctdk** [raintank/grafana#381]
Per #249, (and especially @torkelo's comment at https://github.com/raintank/grafana/issues/249#issuecomment-114995014), people can set up proxy data source and hit internal IP addresses. This is a separate issue from the /debug/vars URL being exposed, so I'm making a new issue for this.

**Comment by Dieterbe** [comment]
i wonder what is the best way to go about this. maybe a grafana config option for some blacklisted ip's/hostnames that aren't allowed? because obviously in some other grafana setups, it's very common to query localhost, if graphite/influx runs on the same machine.

or can this be elegantly solved by something like iptables or cgroups?

**Comment by woodsaj** [comment]
My vote is to solve this with whitelist/blacklist configuration options.

Some users will want to allow everything but a host/network. Others will want to allow only specified network/host.

something like, if in whitelist then allow. if in blacklist then deny.

we could then set a blacklist to 127.0.0.0/8,10.0.0.0/8

**Comment by torkelo** [comment]
opened issue in grafana for this, https://github.com/grafana/grafana/issues/2626

**Comment by woodsaj** [comment]
as noted in https://github.com/raintank/ops/issues/126 we also need to apply the access control in the endpoint discovery service

**Comment by Dieterbe** [comment]
+ form validation
