### ISSUE TITLE
schedule alerting jobs only after we know the collectors have brought in the data

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#384]
let's say you add a monitor at 00:00:00, freq 60s, and have an alert for X collectors being bad during Y steps.
how long should we wait before scheduling alerting jobs? i.e. by what point should we have Y non-null values for all collectors?  (Y+1) * 60 (+ the usual 30s offset?)

right now we ignore created time and schedule jobs straight away, resulting an errors for unknown data.

@woodsaj

**Comment by woodsaj** [comment]
you should schedule them straight away.  The initial state of a monitor is Unknown and the alert jobs should also result in Unknown until there is data available.

Unknowns should NOT be treated as an error.  It is expected that there will sometimes be null data.
Newly created/enabled checks will show have null data but the most common cause is if collectors are offline, this is most prevalent for private collectors that we dont control.

**Comment by Dieterbe** [comment]
shit. that is a good point. also, if you change which collectors to enable for a monitor, previously enabled monitor will return series with a few nulls (right after the change) and full on nulls after a while.  deleting the series wouldn't be a good idea and somehow putting a "hard stop" at the last timestamp seems too complicated. so i guess that would be a 3rd reason.

the reason why i went down this path is because i want to do a bunch of sanity checks on the data returned by graphite (see also https://github.com/raintank/grafana/commit/96da71a5bfb2a57dc7240c9ebb064e76f08c69b5) because i want to make sure there are no hidden "defects" in the data (unexpected nulls, not enough points returned) that may corrupt outcomes of alerting expressions.  I think these checks are generally sane, except for the nulls check, for the reason you pointed out (though the first reason can easily be worked around with a "warmup period"). but it seems your second reason and mine above are strong enough and too hard to properly work around, so i should probably remove the nulls check (as well as the warmup thing i implemented) and assume that the storage won't errorously return nulls when it shouldn't.
in this case though, i think we should we do more strenous testing of graphite/graphite-kairosdb to make sure it behaves properly in a whole bunch of cases.

**Comment by Dieterbe** [comment]
thoughts on the above, @woodsaj ?

**Comment by woodsaj** [comment]
I fixed a few bugs in graphite-kairosdb plugin last week and did a bunch of testing to ensure things were working (i really should write unittests)

The warmup period is still probably a good idea, especially when transitioning from disabled to enabled, as the last known state probably isn't Unknown.  Though, we could also fix this by resetting the state of a monitor when transitioning from/to enabled.

We shouldn't generate errors on unknown data but should definitely keep track of how often it is happening via statsd.   Because unknowns are valid responses, the only way we will know if they are erroneously being returned if if we see sudden change in volume.

**Comment by Dieterbe** [comment]
myeah resetting state seems simpler and more accurate than the warmup period thing.

anyway i know what to do again ;)

**Comment by Dieterbe** [comment]
> Because unknowns are valid responses, the only way we will know if they are erroneously being returned if if we see sudden change in volume.

Remember that currently, we use `litmus.{{.EndpointSlug}}.*.{{.MonitorTypeName | ToLower }}.error_state` as pattern.
So I think in normal operation there's a whole spectrum of volume of nulls that could appear.  Ranging from small (due to blips in collector data coming through, certain collectors going offline or removed from the check config for/by a single customer) to large such as a RT collector going down (affecting everyone's checks) or a bunch of people just stop using certain collectors in their check config for whatever reasons.  And the related change in volume could be anywhere between smooth and subtle to abrupt and big.
Erroreously returning nulls could be due to suble bugs that only manifest rarely, to glaring bugs that manifest a lot (but still not neccesarily at a volume or a rate of change distinguishable from normal operation)
So by simply monitoring volume of nulls overall I don't think you can know what's going on.

On one hand I would like to replace the `*` for the collector pattern in the graphite query to something like `{paris,london,...}`, i.e. listing explicitly the collectors that are configured for the check *and* that are currently marked online.  that would bring the volume of nulls caused by normal operation, as well as their rate of change much lower and expose the more obvious bugs/issues should they appear.
However, all of this "detecting erroreous nulls" stuff is probably based on the wrong premise.  It's all built on the idea that during an alerting run, we want to find evidence of issues/bugs related to graphite-api, and the metrics collection pipeline.  Now I'm thinking we should just stick with `*` and trust that graphite-api/graphite-kairos is solid and if collector data didn't make it into the tsdb properly, we will find out based on our monitoring that we set up around the metrics pipeline and the tsdb.  Another reason to stick with `*` is that it looks like grafana alerting will revolve around "static" alert configuration, where you set up an alert definition once and update it when necessary, and alerting handlers collect the definitions and execute them.  there's no room for logic to query things like "which collectors have you actually enabled in youru config", "which collector is offline", etc.
so let's keep this simple and keep the expression "dumb".

Also, I reread my previous comment and realized tracking the last 2 unique statuses is a little kludgy, it would require multiple queries in a transaction and i'm just looking for a more simple solution here.
maybe we can just institute the rule "don't alert for unknown->ok" and "do alert from unknown->crit/warn", and apply that rule in all 3 cases (new monitor, enabled monitor after a disabled period, and after a litmus outage). It would mean people can get 2 warn/crit notifications in a row and consider the 2nd one redundant, but i think that's such an edge case noth worth optimizing for.

@nopzor1200 , @woodsaj what do you guys think of all this?  the first portion of this comment may be a bit verbose (lots of text with ultimately deciding not much is needed) but i think it's good to give you insight in my thoughts on this.

**Comment by Dieterbe** [comment]
>The warmup period is still probably a good idea, especially when transitioning from disabled to enabled, as the last known state probably isn't Unknown. Though, we could also fix this by resetting the state of a monitor when transitioning from/to enabled.

this could be racey.  if you disable a monitor and we set status=unknown, but right after, an alerting job may execute that had been scheduled just before we disabled it, and overrides the current state again.
in general i would like to get rid of the warmup period, but i'm not sure if it's safe to do so, as you indicate. but i'm not going to think too much about this until after i hear back on everything i've been writing.

**Comment by woodsaj** [comment]
I think resetting the state to 'unknown' when a monitors i disabled or alerting is disabled is the best approach.  This is also really easy to do in the code.

race conditions are definitely possible, but the only way to eliminate them is to query the DB for the monitor definition, including state and enabled flag at the time of job execution.  We have avoided doing this as the query is quite expensive. But we could re-work the scheduling process to address these. 

ie. we could query for just the monitor_ids that need to run in the next minute (or other arbitrary time period) and then feed them into rabbitmq at the times we want to run them.  We can then query the DB for the monitor definitions when we start processing the job. As they should be indexed lookups using the primary Key the queries should be fast.

I personally like to get the OK alerts.  I like to know when problems are resolved.  I also like the idea of receiving an initial OK alert when the state firsts transitions from Unknown to OK, as this ensures that everything is working.  Though i understand why people might not like this.

The idea of querying for `*` instead of a glob `{singapore, seattle}` would be quite complicated.  The problem that we currently have is that once a metrics is seen once, it exists forever and will always show up when a wildcard match is used.  However we can update how our graphite_kairosdb plugin determines what metrics to return.  
Currently, the metric definitions in Elastic dont get updated, this has been fixed in the raintank-metric nsq updates.  With the updates the metricDefintion will be updated at least once every 10minutes.  This will allow us to filter series to return based on how stale they are.  

So if you send a graphite request for data between start and end, we would only return series that have been updated since 30minutes before the start time.  So if a metric hasnt been updated for 5days, it wont show up in a query for the last hour, but it will show up in a query for the last week.

**Comment by Dieterbe** [comment]
> The idea of querying for * instead of a glob {singapore, seattle} would be quite complicated

no we currently query for `*`. i suggested moving **to** the {foo,bar} pattern. but then retracted that idea.

not sure about your graphite-kairos-level filtering idea. on one hand it reduces amount of nulls returned (but what's the value of that?) but it does break the graphite api contract and it hides information that we might find useful at some point (though not sure what that use case would be)

**Comment by woodsaj** [comment]
I am not sure it breaks the graphite contract.  Without filtering stale series, graphite would continue to serve null values for series that are no longer in use.  The alternative is for us to delete the data when series stop being received, but that is far worse as you then would not be able to query time ranges from when the data was being collected.

The benefit that it gives is that graphite would only return data for series that are still being collected, ie it provides the same result as getting the current set of collectors configured for a monitor and querying for them specifically with a glob.

**Comment by Dieterbe** [comment]
> I am not sure it breaks the graphite contract. Without filtering stale series, graphite would continue to serve null values for series that are no longer in use

yes that's exactly how graphite normally behaves. often to the dismay of the user, i also don't think it's formally specified anywhere. but it is what it is.

> The alternative is for us to delete the data when series stop being received, but that is far worse as you then would not be able to query time ranges from when the data was being collected.

far worse indeed

**Comment by woodsaj** [comment]
ok lets do the following.

1. reset the state of a monitor to unknown when creating/enabling/disabling
   We have discussed that there might be race conditions with this, but i am not sure there are.  Any jobs that are queued before we reset the state will not be able to change the state due to the update command limiting the update using the state_change column.
https://github.com/raintank/grafana/blob/master/pkg/services/sqlstore/monitor.go#L880

**Comment by Dieterbe** [comment]
ok so **conclusions reached + some notes for posterity**
* no alerts if state becomes unknown
* reset monitor state to unknown when creating/enabling/disabling: the first two are generally sane, the latter assures if a check was in an error state, and i decided that i didnt want to monitor anymore, the error disappears immediately 
* you were right, state_change prevents races. i forgot about that :+1: 
* note state_change column is set from job.LastPointTs (https://github.com/raintank/grafana/commit/54df2b8b4010d8e55079627511e40f718f2ff797) , not from the actual time the alert ran , which is 30~60s in the past, which is fine for the race condition prevention
* this also implies that if you disable a check (sets state_changed to current time) and then re-enable the check, the first few alerting runs (if you have 1s or 10s data) won't be able to result in state changes even when the data they query for exists.  because the last point they query for, will be prior to the time of enabling. this is a very edge case, and also fair enough behavior. but worth noting.
* this removes the need for warmups, so i'll remove that.
* i think i got confused earlier in the thread about nulls appearing in collector data (which is acceptable, but doesn't result in errors anymore, nor in the check becoming unknown) vs the health check becoming null (unknown), but i think we worked that all out.


I think there's one final point left: I don't think a transition from unknown to OK should result in a notification in all cases. maybe it's acceptable for newly created or re-enabled monitors, but IMHO not if there was an issue with litmus alerting itself (eg data loss on our side). it seems very confusing as an end user to suddenly get an OK out of nowhere, makes you wonder if you missed an earlier critical event or if litmus is buggy or ..

**Comment by woodsaj** [comment]
I still personally like to get all state changes.  If a check has been disabled, and then i enable it, i would want to get a OK notification so that i can be certain that everything is working.

Perhaps we could make "OK" notifications optional via the notification settings?

**Comment by Dieterbe** [comment]
note that i was specifically talking about the case where it was unknown due to internal issues within litmus, not after disable+re-enable

**Comment by Dieterbe** [comment]
i just pushed the fixes to the nsq branch (not to master cause i had weird issues in raintank-docker with everything on master, even after rebuilding all images).
eaed6dac14b385d612a9a300a4fcde5ce34807f8
6547074ec5032714eb01dc387de5e04214963e5d
b4ce0765f73f6bea651b3a2053f1b09e19a1e760

i'm going to close this out. if the unknown->ok ever becomes an issue after a litmus outage, we'll find out..
