### ISSUE TITLE
Health: Nodata displayed despite having data

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#395]
Onboarded a new user today, and nodata is being show for all checks - despite OK events being reported.

![screenshot 2015-08-04 13 09 25](https://cloud.githubusercontent.com/assets/2886187/9067194/0aeafbac-3aaa-11e5-87ae-81cd9e77046a.png)

Also, in Ping dashboard, OK state not being displayed either:
![screenshot 2015-08-04 12 08 13](https://cloud.githubusercontent.com/assets/2886187/9067226/2832aa7a-3aaa-11e5-992e-732e4e21aa0d.png)

**Comment by Dieterbe** [comment]
is this still an issue? @mattttt are you still seeing this?

i tried reproducing it on dev, but the 10s based checks got a status within about a minute, and the http/https that get data every 60s and need 2 steps took about 3 minutes, so it seems it works fine, though i'm not sure why and what the original issue was, so that's a bit discomforting. maybe @woodsaj knows?

also, maybe we should rename NODATA to "unknown" or something.  NODATA seems confusing because there is data. all kinds of data in fact, just not sufficient data as per your the check configuration to say what the current state is.

**Comment by woodsaj** [comment]
i am fairly sure that this was just because alerting was turned off.  But if it is still happening we will definitely look into it.

**Comment by mattttt** [comment]
To your point @Dieterbe, took a look on dev-portal and production, on a couple different accounts, and looks great for existing accounts with enough data. 

When I create a new endpoint however, that's when it rears its head. Is it possible to introduce some awareness of newly created endpoints, so when it's still collecting enough data to make a decision, we can articulate that to the user?

I think we're on the same page here, but I dont know how to address it.

**Comment by Dieterbe** [comment]
i'm pretty sure there is a ticket somewhere discussing optimizing the wording a bit of that monitor status in the UI but couldn't find it. we also spoke about it with Raj in NYC (well. def me and Raj) and pretty sure the main outcome there was we need to find a way that if unknown, we can tell the user if it's because of something they did and should fix, or whether it's because we're experiencing a problem.
in this case it's neither and simply because some more time needs to elapse.

anyway, backend wise we have ok, warn, crit, unknown. this is pretty standard, all monitoring tools ever pretty much do this.  one approach would be extending this with a few different versions of unknown.  but i rather keep this part simple and standard.
From what I see, if the `/monitors` api call would just return when the monitor is created (right now it just shows updated), then the frontend could just check if state is unknown and `now <= created + step*freq + 60`, then say "unknown because the required data hasn't made it in yet".
OTOH that would require relying on the users clock, which is unreliable and could cause the wrong status to be shown.
so maybe it's up to the api call could just support additional state codes, but that richer model wouldn't be in the db. what do you think @woodsaj ?

**Comment by woodsaj** [comment]
I think changing the wording from "No Data" to "Insufficient Data" would go a long way.

Without extending the data model to track additional state change information, we could easily enough display a different message (perhaps, "pending") if state is unknown AND update_time is recent.  This is not a perfect solution, but i would argue that it is good enough.

**Comment by woodsaj** [comment]
affirmative.

**Comment by woodsaj** [comment]
![image](https://cloud.githubusercontent.com/assets/8415072/9583911/655baf22-5040-11e5-9ebc-80e8153dafe0.png)

How does this look to you @mattttt

**Comment by mattttt** [comment]
@woodsaj Works for me.
