### ISSUE TITLE
Traceroute from a Collector

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#396]
For discussion...

This has come up a couple times, but clients have requested the ability to traceroute from a collector to an endpoint, so they can see the network path a collector takes. 

I envision this functionality existing on the Collector Summary page, and triggering a popup/external window that communicates with the collector, opens a connection, and reports the traceroute back in real time.

**Comment by Dieterbe** [comment]
note that routes may be changing at all times. in fact, the reason why a ping check temporarily fails while it should normally succeed may be exactly due to a temporary routing change.
so an "after the fact" traceroute could be very misleading. OTOH doing a traceroute everytime state changes from ok to error might be a bit too resource intensive? idea for a paying feature? thoughts @woodsaj @nopzor1200 @ctdk ?

**Comment by woodsaj** [comment]
Adding adhoc traceroutes shouldn't be too hard.  Once we have it wouldn't be too hard integrate them with alerting, though would obviously need to charge appropriately to recover costs.

**Comment by nopzor1200** [comment]
I think it's interesting to be able to do this "on demand" and focus on that use case initially.

Later we can decide to trigger either automatically (with an alert), or periodically, or whatever we want, for certain clients.

Agreed re: cost recovery, but that's a larger issue we're dealing with atm :)

**Comment by ctdk** [comment]
Seems reasonable to me. Pingdom provides that very function, actually, and I often found it useful as a way to tell what the problem was, be it firewall mishap, some problem between the monitor and the Internap servers, or something going horribly wrong trying to get into Internap.
