### ISSUE TITLE
rabbitmq consumer does not continue consuming after channel is lost and re-established

### ISSUE THREAD

**Issue by woodsaj** [raintank/grafana#400]
we need to add https://github.com/raintank/grafana/blob/master/pkg/services/rabbitmq/consumer.go#L39-L41 to https://github.com/raintank/grafana/blob/master/pkg/services/rabbitmq/consumer.go#L105-L107

**Comment by woodsaj** [comment]
@ctdk  why is this same change committed to two different branches?
Also the commit is wrong, see the comment on https://github.com/raintank/grafana/commit/6bfc1da27619babc8b56c604ebe1792ee8c8de45

**Comment by ctdk** [comment]
Saw the comment there, will be doing that now. It was behaving correctly after that change, which made me think it was the right order. The reason you're seeing this same commit in two branches is because I made a new branch and cherry picked this one into it, because the "mu" fix isn't actually necessary to fix the logstash problem, so I'm going to throw that branch away.
