### ISSUE TITLE
Cannot trigger dropdown on collector list

### ISSUE THREAD

**Issue by bulletfactory** [raintank/grafana#463]
Cannot use the 3 dots on the right to trigger dropdown on collector list page (view/configure/delete).

Seems to be an "overflow:hidden" issue on .rt-list-header

**Comment by mattttt** [comment]
This has been taken away temporarily, partially because it's a bit complicated (with clicking the whole row to get into detail) and partially because users found it confusing. Has been replaced on some screens with a gear, and on the main endpoint list, removed entirely. 

Assigning this to me to remove from collector list and then will close.
