### ISSUE TITLE
alert icons don't load + js error

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#507]
saw this today on dev:
note the icons for the 3rd endpoint.
![bug](https://cloud.githubusercontent.com/assets/20774/10670172/56b6c250-78b2-11e5-89db-a6940b32bdf4.png)

**Comment by Dieterbe** [comment]
when i refresh it now, it works fine. the icons show up, no more error.

**Comment by woodsaj** [comment]
this is due to a race condition in the code.

https://github.com/raintank/grafana/blob/master/public/plugins/raintank/features/endpointSummaryCtrl.js#L19-L23

We asynchronously fetch the monitor_types and the endpoints.  Once the endpoints have been fetched we process them assuming that monitor_types have also completed, but there are no guarantees that this is true.
