### ISSUE TITLE
Color Override on Admin Account

### ISSUE THREAD

**Issue by mattttt** [raintank/grafana#520]
There have been a few times where I've caught myself almost making changes on a client's organization as I bounce between open tabs. With that, do you suppose we can put some kind of check in there that says:

If logged in UserID = 1 AND OrgID != 1, then:

![screenshot 2015-11-05 16 34 40](https://cloud.githubusercontent.com/assets/2886187/10982466/5788df54-83db-11e5-9a26-0f35e37add6e.png)

This is just a quick and dirty mockup, we'll make it look better. Anyone else see the value in this?

**Comment by nopzor1200** [comment]
Maybe a settable badge or background color per Org would be the best way to accomplish this across Grafana and raintank.

 It solves this problem and allows for some visual customization/distinction on a per-Org basis that would be useful to people for all sorts of reasons (branding, distinguishing, etc)

Otherwise might have to introduce raintank-specific functionality since a lot of small Grafana users might only have 1 user (admin). Switching admin to a "abnormal" icon implies that we want to discourage that behavior?

**Comment by bulletfactory** [comment]
Do we think leveraging/using the avatar for users and orgs which already exist in the sidebar would be too subtle to notice?

**Comment by woodsaj** [comment]
how is logging in as the Grafana Admin, with the "admin" role on may different Orgs different to logging in as any other user with the "admin" role on may different orgs?  Is the problem not the same for all users.

Sounds to me that the problem is simply that the "current Org" is not prominent enough in the UI.
