### ISSUE TITLE
incorrect display of errors 

### ISSUE THREAD

**Issue by Dieterbe** [raintank/grafana#80]
1) dns <100% but error bars are all green?
2) ping 100.00% in orange?
![vague-errors-summary](https://cloud.githubusercontent.com/assets/20774/7550411/c1a46122-f62f-11e4-9f73-5273a9e097d7.png)
3) this one should speak for itself:

![errors-incorrect](https://cloud.githubusercontent.com/assets/20774/7550412/c676debe-f62f-11e4-88b4-fdeda6811271.png)

**Comment by Dieterbe** [comment]
i can repro number 1 with max datapoints to 10, graphite returns (in order) 6 nulls, 3 100's and the last point is 99.99609984399376

**Comment by nopzor1200** [comment]
Great finds. I think all issues here are addressed in a new version of this dashboard:

Great feedback

Three separate bugs in this dashboard that I think are all fixed.

1) decimal precision on the singlestat panel. Was set to 2. So 99.999% gets rounded up to 100%. That's why 100.00% showed up as orange and not green 

2) If there is an extremely low ratio of errors:oks, then the errors can get lost in the sea of green. So I think it's better to explicitely plot errors/warns and not explicitely plot oks (I just changed the background of the graph to green),

3) I also added a consolidateby(sum) to these panels; should have had them before I think. 

Between all these 3 fixes I think all these issues are resolved.

Check it out on the rt-endpoint-summaryv2 dashboard in your account

**Comment by Dieterbe** [comment]
i think a percentage with 3 decimals looks weird, and the level of detail becomes too much.  also it wouldn't be a proper fix anyway, it only takes a value like 99.9999 (which is possible if you cover a larger timeframe) and the problem re-appears again, sure you can add another decimal but then the issue will reappear if another 9 gets in the value (possible with a singular error and a large enough timeframe) and so on. i would rather just round down to the lower hundredth of a percent, so that values like 99.999 or 99.9999 become 99.99%

**Comment by Dieterbe** [comment]
or... could we apply the thresholds that are used for the visualization to the rounded values that are shown? that way it will always be consistent and we can keep rounding to the nearest percent of a percent. @torkelo ?

**Comment by woodsaj** [comment]
i think it would be best to adjust the threshold values.  Anything above 99.99 should be considered ok.

**Comment by nopzor1200** [comment]
@woodsaj we could certainly change the color threshold to 99.99 for default, but the same problem will keep happening no matter what we set it to. At least I think so.

I think the behavior in singlestat needs to change according to what @dieterbe is saying: grafana needs to use the same value *AFTER* it is rounded to the decimal places that the user specifies in the panel, for *BOTH* the value display and the threshold coloring. I think it's just a small bug in grafana that it uses different values for each.

**Comment by torkelo** [comment]
Fixed in grafana-upstream, https://github.com/grafana/grafana/issues/1983

threshold checks are done after rounding of the main value, rounding is done with same number of decimals as the value shown is.

**Comment by nopzor1200** [comment]
Thanks @torkelo! Closing this one out.

**Comment by Dieterbe** [comment]
so to clarify the closing of this ticket, torkels fix should address my 2nd concern, we can talk about 1 and 3 in #81
