### ISSUE TITLE
more endpoint dashboard tweaks

### ISSUE THREAD

**Issue by nopzor1200** [raintank/grafana#81]
in rt-endpoint-ping dashboard:
 in the ping response range panel:
   - add consolidateby(max) to max ping latency metric
   - add consolidateby(min) to min ping latency metric

in all dashboards:
 in the status bar panel: 
   - add consolidateby(sum) to all metrics

**Comment by nopzor1200** [comment]
Also lets set MaxDataPoints to auto (remove the explicit value) from all panels except the error bar panels

**Comment by woodsaj** [comment]
fixed the Ping panel and update the maxDatapoints.  

But adding consolidatedBy(sum) to the status bar is not right, it should be left to use the default avg consolidateBy.  If you use sum and the data is consolidated the error bar values will no longer be the number of collectors.  The data then becomes very confusing.

**Comment by woodsaj** [comment]
ok. I see why you wanted to use consolidateBy(sum).  Currently when the data is being aggregated the numbers shown are not always right due to rounding.

using consolidateBy(sum) doesnt really help much. Though the ratio of the numbers would be correct, the numbers themselves would not be accurate.

I think the best option here is to have the frontend adjust the numbers to be a percentage. The graph is  already using the 'stack as percentage' option, so perhaps we could extend that feature to also affect the tooltip so that percentages are shown.

**Comment by Dieterbe** [comment]
would http://graphite.readthedocs.org/en/1.0/functions.html#graphite.render.functions.asPercent help?

**Comment by nopzor1200** [comment]
asPercent might help thanks @Dieterbe 

But there's a bigger problem that I see in doing it as a percentage or relative ok:error bars. When you look at long time periods over a lot of collectors (we're going to have a lot more than 10), you can't visually see when you have a small amount of errors. It gets lost in a sea of green. That really kind of sucks imo.

What do you guys think of just showing errors, and not ratio of ok:error

We could also put them on separate Y axis. That might be a neat way to solve the problem.

**Comment by nopzor1200** [comment]
The idea in my head behind the error bar was that you'd (eventually) be able to click any bar and be taken to the specific errors in question. 

We haven't really talked about that much (well other than me mentioning to @mattttt  I dont think). I think something like that is imminently achievable once #44 and #88 are done, and it'll be a really nice way (imo) to tie this all together.

eg. if I'm looking at a month of HTTP for nopzair.com in Europe I'd see maybe 30 bars each representing 1 day of time. If I click on 1 of the bars, I'd go to the event dashboard with a filter for that day, for that endpoint, and for the Europe collectors. I'd be able to view the specific errors in question. The idea works really well when zooming around and looking at outages or incidents from the endpoint dashboard.

When I think of this possibility the idea of only showing errors, and the idea of consolidatebysum() makes more sense because each bar is a "count of errors" that you can click on to examine further.

**Comment by Dieterbe** [comment]
after discussing with Raj I think sum-consolidation, showing OK's, and a log scale seems like the best way.

to fully understand the reasoning behind that, i'm going to try to take a bit of a more structured approach of the various concerns, the solutions, and their intersections

concerns:
1) for large discrepancies (some timeperiods many many errors, other timeperiods very few errors), should we be able to still see the tiny amount? I think it would be nice, but not super important.
after all, if you have large amounts of errors, then the tiny amount should be of negligible concern.

2) seeing every possible low-errors value, even in context of long timeframes and assuming no large-errors values exist.

3) sense of scale. i like to look at the viz with the notion in my head that a certain amount of red corresponds to a certain fraction of error/ok. example: fully red bar means 100% errors, no ok's, half a red bar means an even split, etc.

4) explicit ok states: do we also render greens for ok's? i think we generally agree this is a nice feature and gives some extra faith, otherwise maybe the monitoring system is having issues.
however once we go prod it'd be nice to have background markers or something to denote when the platform itself was having issues and data might be unreliable, but even then, explicit ok's are still valuable.

5) what is shown on the hover: would be nice if it's total errors, as per @nopzor1200's remarks where it links to event panel with corresponding amounts.

options:

A the way it is right now, with avg consolidation
B like A, but sum consolidation
C sum consolidation, but only show errors (basically means yMax is highest val seen)


ABC don't do a very good job at 1, but that isn't neccesarily a bad thing. a log scale could help, though does impact 3 to some extent. 

AB don't support 2 at all. basically due to showing the OK's. log scale helps. this is where C's value shows.

AB are great at 3, C not.
only AB can do 4.
5 seems a bit dependent on what the panel lets us do but I think should be ok with both B and C, not so much A.

**Comment by Dieterbe** [comment]
@nopzor1200 my remark that `log(5)+log(5) != log(10)` (in fact, this was interesting, as per wikipedia, it equals the product, so `log(5)+log(5) == log(5*5)`) was actually irrelevant because the logarithm-based position on the y-axis gets calculated after the summing due to the stacking of the input series, not on the individual inputs, so this is not a concern.

@nopzor1200 & @woodsaj i saved my suggested approach at https://portal.raintank.io/dashboard/db/rt-endpoint-summary-copy
if you look at http errors for ebay the last 7 days, that's a good demo.
i added consolidateby sum to the http errors panel, and applied a log scale, the lowest log base was 10, which makes the logarithm fairly aggressive, i asked @torkelo to add a lower log base like 2 which should be less aggressive. i also had to reorder the metrics so that the errors were on the bottom, for the log to behave in the desired way.
![ebay-http-errors](https://cloud.githubusercontent.com/assets/20774/7633181/9ce588a8-fa20-11e4-8438-1f1e35fdcfa2.png)

**Comment by Dieterbe** [comment]
on a related usability note, when I saw "http 98.15%" in RED i thought at first that 98.15% were failing.
i suspect i'm not the only one whose brain is wired this way.
i have a few ideas on how we could make this clearer
![mockup](https://cloud.githubusercontent.com/assets/20774/7633983/f020de6e-fa25-11e4-8fc7-0727ded7cc82.png)
a is current approach
b basically just clarifies by making both categories explicit
c is a bit nicer perhaps, by visually clarifying the fraction that is ok vs the fraction that is erroring, it clarifies a bit compared to a i think
d is actually my favorite, i think.  it's based on the realisation that the coloring of the error % in the block above is a bit arbitrarily predefined, not necessarily what the user expects, and is a very crude visualisation.  in fact, we have the error bars below that have a very nice green/red ratio that instantly convey a lot of information about the ratios of good vs bad, in a way that requires little brain power to comprehend.  so we can get rid of the entire top block and simply put the % somewhere.

**Comment by nopzor1200** [comment]
Ok so what did we decide here?

1. Nix the background colors. Stick with green for 100% and black for all other values. Otherwise we're reimplementing alerting of sorts and that doesn't seem right to pick arbitrary thresholds

2. Sum consolidation because we will go the event panel and view that particular number of errors

3. Possibly log scale to make the errors pop more if its a low percentage

@Dieterbe and @mattttt does this sound right?

**Comment by Dieterbe** [comment]
i think so yes, curious for the arrival of log base 2 in raintank grafana to try out the log scale.

**Comment by mattttt** [comment]
Some tweaks on Friday afternoon, saved in this branch:
https://github.com/raintank/grafana/tree/mattttt-summary-dash-patch1

**Comment by nopzor1200** [comment]
Closing this out. Anthony said he merged these endpoint-summary changes into master
